apiVersion: v1
kind: Service
metadata:
  name: pipeline-example-backend-dev
  labels:
    app: pipeline-example-backend-dev
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: pipeline-example-backend-dev
  sessionAffinity: None
