name: Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Unit test
        run: |
          go test ./... -covermode=count -coverprofile=coverage.out
          go test ./... -coverprofile=unit-test.out -json > unit-test.json
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out
          TOTAL_COV=$(go tool cover -func=coverage.out | grep total | tr -d '%' | awk '{print $3}')
          echo "Total Coverage: $TOTAL_COV"
          cat unit-test.json
          cat coverage.out
