name: Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  IMAGE_TAG: chalvinwz/pipeline-example-backend

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Unit test
        run: |
          go test ./... -covermode=count -coverprofile=coverage.out
          go test ./... -coverprofile=unit-test.out -json > unit-test.json

      - name: Code coverage
        run: |
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out
          echo $GITHUB_SHA
          echo ${GITHUB_SHA}

  # build-image:
  #   needs: unit-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to Dockerhub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{secrets.DOCKERHUB_USERNAME}}
  #         password: ${{secrets.DOCKERHUB_TOKEN}}

  #     - name: Build and push image
  #       run: |
  #         docker build -t ${{env.IMAGE_TAG}} .
  #         docker push ${{env.IMAGE_TAG}}
