name: Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Unit test
        run: |
          mkdir coverage
          go test ./... -covermode=count -coverprofile=coverage/coverage.out
          go test ./... -coverprofile=coverage/unit-test.out -json > coverage/unit-test.json || return 0
          go tool cover -func=coverage/coverage.out
          go tool cover -html=coverage/coverage.out
