name: Pipeline

on:
  push:
    branches: [master, dev]
  # pull_request:
  #   branches: [master]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Unit test
        run: |
          go test ./... -covermode=count -coverprofile=coverage.out
          go test ./... -coverprofile=unit-test.out -json > unit-test.json

      - name: Code coverage
        run: |
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        run: az group list

      # - uses: azure/docker-login@v1
      #   with:
      #     login-server: contoso.azurecr.io
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      # - run: |
      #     docker build . -t contoso.azurecr.io/nodejssampleapp:${{ github.sha }}
      #     docker push contoso.azurecr.io/nodejssampleapp:${{ github.sha }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 'Deploy to Azure Container Instances'
  #       uses: 'azure/aci-deploy@v1'
  #       with:
  #         resource-group: contoso
  #         dns-name-label: url-for-container
  #         image: contoso.azurecr.io/nodejssampleapp:${{ github.sha }}
  #         cpu: 1   #Optional
  #         memory: 0.1   #Optional
  #         registry-username: ${{ secrets.REGISTRY_USERNAME }}
  #         registry-password: ${{ secrets.REGISTRY_PASSWORD }}
  #         name: contoso-container
  #         location: 'west us'

  # build-image:
  #   needs: unit-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to Dockerhub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{secrets.DOCKERHUB_USERNAME}}
  #         password: ${{secrets.DOCKERHUB_TOKEN}}

  #     - name: Build and push image
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: chalvinwz/pipeline-example-backend
