name: Pipeline

on:
  push:
    branches: [master, dev]
  # pull_request:
  #   branches: [master]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Unit test
        run: |
          go test ./... -covermode=count -coverprofile=coverage.out
          go test ./... -coverprofile=unit-test.out -json > unit-test.json

      - name: Code coverage
        run: |
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out

  build-image:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: pipelinexample.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and Push image to ACR
        run: |
          docker build . -t pipelinexample.azurecr.io/pipeline-example-backend:${{ github.sha }}
          docker push pipelinexample.azurecr.io/pipeline-example-backend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: pipeline-example
          dns-name-label: pipeline-example-backend
          image: pipelinexample.azurecr.io/pipeline-example-backend:${{ github.sha }}
          cpu: 1
          memory: 1.5
          registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          name: pipeline-container
          location: 'east us'

  # build-image:
  #   needs: unit-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to Dockerhub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{secrets.DOCKERHUB_USERNAME}}
  #         password: ${{secrets.DOCKERHUB_TOKEN}}

  #     - name: Build and push image
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: chalvinwz/pipeline-example-backend
